"""My hand labels for the 210 golden examples.

Produced by reading every message against config/taxonomy.yaml. Recorded as
source rather than a bare CSV so the reasoning is reviewable and diffable.

ROUTE REASON CODES
  Escalate:
    account_security      identity or account ownership at stake
    money_dispute         disputed transaction, refund, or failed payment
    account_lookup        needs account-specific data a public bot cannot see
    repeat_contact        customer states they have already been failed
    churn_risk            explicit threat to cancel
    sensitive_content     moderation or safety judgement required
    creator_account       artist/label matter, not consumer support
    hostile_venting       abusive with no actionable request
  Auto:
    troubleshooting       standard diagnostic steps apply
    informational         answerable from public policy or product facts
    content_licensing     availability question with a standard explanation
    feature_feedback      feature request or product opinion
    acknowledgement       thanks, praise, or closing; no action needed
    no_action             contentless or off-topic; simple acknowledgement

BOUNDARY CALLS I MADE, recorded because a second annotator could reasonably
differ and these drive a chunk of the disagreement:
  * Shuffle complaints (g086, g116) -> playback_failure, not playlist_library.
    Shuffle is playback behaviour; the library itself is intact.
  * "App crashes" WITH a named platform (g107, g132) -> device_compat;
    without one (g018, g087) -> playback_failure. This follows the taxonomy's
    own negative example and is the single largest source of near-misses.
  * Country-level service availability (g052, g153, g205) -> other, not
    content_missing. content_missing is about catalogue items, not markets.
  * Payment-method update failures (g043, g044, g138, g177) -> billing_charge.
    The taxonomy defines billing_charge as a *disputed* transaction, which
    these are not. This is a genuine taxonomy gap, recorded in the report.
  * Non-English messages (g032, g167) are labelled by their actual intent, not
    dumped in `other`. Language is orthogonal to intent; the taxonomy text
    saying otherwise is wrong and is corrected in the report.
"""

# golden_id: (intent, route, reason_code)
LABELS: dict[str, tuple[str, str, str]] = {
    "g000": ("other", "escalate", "hostile_venting"),
    "g001": ("subscription_manage", "auto", "informational"),
    "g002": ("account_access", "auto", "troubleshooting"),
    "g003": ("acknowledgement", "auto", "acknowledgement"),
    "g004": ("account_access", "escalate", "account_lookup"),
    "g005": ("other", "escalate", "repeat_contact"),
    "g006": ("billing_charge", "escalate", "money_dispute"),
    "g007": ("account_access", "escalate", "account_lookup"),
    "g008": ("device_compat", "auto", "troubleshooting"),
    "g009": ("other", "auto", "no_action"),
    "g010": ("content_missing", "auto", "content_licensing"),
    "g011": ("device_compat", "auto", "informational"),
    "g012": ("billing_charge", "escalate", "money_dispute"),
    "g013": ("content_missing", "auto", "content_licensing"),
    "g014": ("account_access", "escalate", "account_security"),
    "g015": ("other", "auto", "no_action"),
    "g016": ("feature_request", "auto", "feature_feedback"),
    "g017": ("feature_request", "auto", "feature_feedback"),
    "g018": ("playback_failure", "auto", "troubleshooting"),
    "g019": ("device_compat", "auto", "troubleshooting"),
    "g020": ("acknowledgement", "auto", "acknowledgement"),
    "g021": ("other", "auto", "creator_account"),
    "g022": ("playback_failure", "auto", "troubleshooting"),
    "g023": ("other", "auto", "informational"),
    "g024": ("other", "escalate", "repeat_contact"),
    "g025": ("feature_request", "auto", "feature_feedback"),
    "g026": ("account_access", "escalate", "account_lookup"),
    "g027": ("playlist_library", "auto", "troubleshooting"),
    "g028": ("subscription_manage", "escalate", "account_lookup"),
    "g029": ("billing_charge", "escalate", "money_dispute"),
    "g030": ("content_missing", "auto", "content_licensing"),
    "g031": ("subscription_manage", "auto", "informational"),
    "g032": ("billing_charge", "escalate", "money_dispute"),
    "g033": ("other", "auto", "no_action"),
    "g034": ("content_missing", "auto", "content_licensing"),
    "g035": ("playback_failure", "auto", "troubleshooting"),
    "g036": ("playback_failure", "auto", "troubleshooting"),
    "g037": ("subscription_manage", "auto", "informational"),
    "g038": ("device_compat", "auto", "troubleshooting"),
    "g039": ("device_compat", "auto", "troubleshooting"),
    "g040": ("billing_charge", "escalate", "money_dispute"),
    "g041": ("other", "auto", "no_action"),
    "g042": ("device_compat", "auto", "troubleshooting"),
    "g043": ("billing_charge", "escalate", "money_dispute"),
    "g044": ("billing_charge", "escalate", "account_lookup"),
    "g045": ("other", "auto", "no_action"),
    "g046": ("playback_failure", "auto", "troubleshooting"),
    "g047": ("content_missing", "auto", "content_licensing"),
    "g048": ("acknowledgement", "auto", "acknowledgement"),
    "g049": ("feature_request", "auto", "feature_feedback"),
    "g050": ("device_compat", "auto", "troubleshooting"),
    "g051": ("content_missing", "auto", "content_licensing"),
    "g052": ("other", "auto", "informational"),
    "g053": ("device_compat", "auto", "informational"),
    "g054": ("feature_request", "auto", "feature_feedback"),
    "g055": ("billing_charge", "escalate", "money_dispute"),
    "g056": ("other", "escalate", "repeat_contact"),
    "g057": ("account_access", "escalate", "account_security"),
    "g058": ("other", "auto", "no_action"),
    "g059": ("other", "escalate", "sensitive_content"),
    "g060": ("feature_request", "auto", "feature_feedback"),
    "g061": ("playlist_library", "auto", "troubleshooting"),
    "g062": ("subscription_manage", "auto", "informational"),
    "g063": ("device_compat", "auto", "informational"),
    "g064": ("subscription_manage", "escalate", "account_lookup"),
    "g065": ("acknowledgement", "auto", "acknowledgement"),
    "g066": ("subscription_manage", "auto", "informational"),
    "g067": ("playlist_library", "auto", "troubleshooting"),
    "g068": ("playlist_library", "auto", "troubleshooting"),
    "g069": ("account_access", "escalate", "account_security"),
    "g070": ("acknowledgement", "auto", "acknowledgement"),
    "g071": ("subscription_manage", "escalate", "account_lookup"),
    "g072": ("subscription_manage", "auto", "informational"),
    "g073": ("playback_failure", "auto", "troubleshooting"),
    "g074": ("feature_request", "auto", "feature_feedback"),
    "g075": ("playlist_library", "auto", "troubleshooting"),
    "g076": ("subscription_manage", "escalate", "account_lookup"),
    "g077": ("content_missing", "auto", "content_licensing"),
    "g078": ("content_missing", "auto", "content_licensing"),
    "g079": ("content_missing", "auto", "content_licensing"),
    "g080": ("acknowledgement", "auto", "acknowledgement"),
    "g081": ("billing_charge", "escalate", "money_dispute"),
    "g082": ("account_access", "escalate", "account_security"),
    "g083": ("device_compat", "auto", "troubleshooting"),
    "g084": ("billing_charge", "escalate", "money_dispute"),
    "g085": ("subscription_manage", "escalate", "repeat_contact"),
    "g086": ("playback_failure", "auto", "troubleshooting"),
    "g087": ("playback_failure", "auto", "troubleshooting"),
    "g088": ("acknowledgement", "auto", "acknowledgement"),
    "g089": ("playback_failure", "auto", "troubleshooting"),
    "g090": ("feature_request", "auto", "feature_feedback"),
    "g091": ("playback_failure", "auto", "troubleshooting"),
    "g092": ("account_access", "escalate", "account_security"),
    "g093": ("feature_request", "auto", "feature_feedback"),
    "g094": ("subscription_manage", "escalate", "account_lookup"),
    "g095": ("playlist_library", "auto", "troubleshooting"),
    "g096": ("billing_charge", "escalate", "money_dispute"),
    "g097": ("feature_request", "auto", "feature_feedback"),
    "g098": ("other", "auto", "creator_account"),
    "g099": ("acknowledgement", "auto", "acknowledgement"),
    "g100": ("acknowledgement", "auto", "acknowledgement"),
    "g101": ("playback_failure", "auto", "troubleshooting"),
    "g102": ("device_compat", "auto", "troubleshooting"),
    "g103": ("billing_charge", "escalate", "money_dispute"),
    "g104": ("feature_request", "auto", "feature_feedback"),
    "g105": ("account_access", "escalate", "account_security"),
    "g106": ("feature_request", "auto", "feature_feedback"),
    "g107": ("device_compat", "auto", "troubleshooting"),
    "g108": ("account_access", "escalate", "account_security"),
    "g109": ("billing_charge", "escalate", "money_dispute"),
    "g110": ("content_missing", "auto", "content_licensing"),
    "g111": ("device_compat", "auto", "troubleshooting"),
    "g112": ("playlist_library", "auto", "troubleshooting"),
    "g113": ("device_compat", "auto", "troubleshooting"),
    "g114": ("feature_request", "auto", "feature_feedback"),
    "g115": ("content_missing", "auto", "content_licensing"),
    "g116": ("playback_failure", "auto", "troubleshooting"),
    "g117": ("feature_request", "auto", "feature_feedback"),
    "g118": ("feature_request", "auto", "feature_feedback"),
    "g119": ("account_access", "auto", "acknowledgement"),
    "g120": ("content_missing", "auto", "content_licensing"),
    "g121": ("subscription_manage", "escalate", "account_lookup"),
    "g122": ("feature_request", "auto", "feature_feedback"),
    "g123": ("other", "auto", "informational"),
    "g124": ("content_missing", "auto", "content_licensing"),
    "g125": ("feature_request", "auto", "feature_feedback"),
    "g126": ("billing_charge", "escalate", "money_dispute"),
    "g127": ("content_missing", "auto", "content_licensing"),
    "g128": ("device_compat", "auto", "troubleshooting"),
    "g129": ("billing_charge", "escalate", "money_dispute"),
    "g130": ("feature_request", "auto", "feature_feedback"),
    "g131": ("playback_failure", "auto", "troubleshooting"),
    "g132": ("device_compat", "auto", "troubleshooting"),
    "g133": ("feature_request", "auto", "feature_feedback"),
    "g134": ("billing_charge", "escalate", "money_dispute"),
    "g135": ("account_access", "escalate", "account_security"),
    "g136": ("playback_failure", "auto", "troubleshooting"),
    "g137": ("other", "escalate", "creator_account"),
    "g138": ("billing_charge", "escalate", "money_dispute"),
    "g139": ("billing_charge", "escalate", "money_dispute"),
    "g140": ("playlist_library", "auto", "troubleshooting"),
    "g141": ("playback_failure", "auto", "troubleshooting"),
    "g142": ("content_missing", "auto", "content_licensing"),
    "g143": ("device_compat", "auto", "troubleshooting"),
    "g144": ("device_compat", "auto", "troubleshooting"),
    "g145": ("billing_charge", "escalate", "money_dispute"),
    "g146": ("billing_charge", "escalate", "money_dispute"),
    "g147": ("subscription_manage", "auto", "informational"),
    "g148": ("acknowledgement", "auto", "acknowledgement"),
    "g149": ("subscription_manage", "escalate", "account_lookup"),
    "g150": ("subscription_manage", "escalate", "account_lookup"),
    "g151": ("subscription_manage", "escalate", "account_lookup"),
    "g152": ("device_compat", "auto", "troubleshooting"),
    "g153": ("other", "escalate", "hostile_venting"),
    "g154": ("billing_charge", "escalate", "money_dispute"),
    "g155": ("billing_charge", "escalate", "money_dispute"),
    "g156": ("feature_request", "auto", "feature_feedback"),
    "g157": ("feature_request", "auto", "feature_feedback"),
    "g158": ("acknowledgement", "auto", "acknowledgement"),
    "g159": ("device_compat", "auto", "troubleshooting"),
    "g160": ("content_missing", "auto", "content_licensing"),
    "g161": ("account_access", "escalate", "account_security"),
    "g162": ("feature_request", "auto", "feature_feedback"),
    "g163": ("device_compat", "auto", "troubleshooting"),
    "g164": ("playback_failure", "auto", "troubleshooting"),
    "g165": ("acknowledgement", "auto", "acknowledgement"),
    "g166": ("content_missing", "auto", "content_licensing"),
    "g167": ("subscription_manage", "auto", "informational"),
    "g168": ("playback_failure", "auto", "troubleshooting"),
    "g169": ("device_compat", "auto", "troubleshooting"),
    "g170": ("subscription_manage", "escalate", "account_lookup"),
    "g171": ("account_access", "escalate", "account_security"),
    "g172": ("feature_request", "auto", "feature_feedback"),
    "g173": ("playback_failure", "auto", "troubleshooting"),
    "g174": ("billing_charge", "escalate", "money_dispute"),
    "g175": ("playlist_library", "auto", "troubleshooting"),
    "g176": ("billing_charge", "escalate", "money_dispute"),
    "g177": ("billing_charge", "escalate", "money_dispute"),
    "g178": ("billing_charge", "escalate", "money_dispute"),
    "g179": ("other", "auto", "feature_feedback"),
    "g180": ("feature_request", "auto", "feature_feedback"),
    "g181": ("device_compat", "auto", "troubleshooting"),
    "g182": ("content_missing", "auto", "content_licensing"),
    "g183": ("playlist_library", "auto", "troubleshooting"),
    "g184": ("playback_failure", "auto", "troubleshooting"),
    "g185": ("feature_request", "auto", "feature_feedback"),
    "g186": ("billing_charge", "escalate", "money_dispute"),
    "g187": ("playback_failure", "escalate", "repeat_contact"),
    "g188": ("feature_request", "auto", "feature_feedback"),
    "g189": ("account_access", "escalate", "account_security"),
    "g190": ("content_missing", "auto", "content_licensing"),
    "g191": ("playback_failure", "auto", "troubleshooting"),
    "g192": ("feature_request", "auto", "feature_feedback"),
    "g193": ("feature_request", "escalate", "churn_risk"),
    "g194": ("subscription_manage", "auto", "informational"),
    "g195": ("content_missing", "auto", "content_licensing"),
    "g196": ("feature_request", "auto", "feature_feedback"),
    "g197": ("device_compat", "auto", "troubleshooting"),
    "g198": ("subscription_manage", "auto", "informational"),
    "g199": ("playback_failure", "escalate", "churn_risk"),
    "g200": ("billing_charge", "escalate", "money_dispute"),
    "g201": ("subscription_manage", "escalate", "account_lookup"),
    "g202": ("account_access", "escalate", "account_security"),
    "g203": ("device_compat", "auto", "troubleshooting"),
    "g204": ("feature_request", "auto", "feature_feedback"),
    "g205": ("other", "auto", "informational"),
    "g206": ("device_compat", "auto", "informational"),
    "g207": ("playback_failure", "auto", "troubleshooting"),
    "g208": ("content_missing", "auto", "content_licensing"),
    "g209": ("feature_request", "auto", "feature_feedback"),
}
